#+title: Chance README
#+date: <2021-07-24 Sat>
#+author: William Clifford
#+email: will@wobh.org
#+language: en
#+select_tags: export
#+exclude_tags: noexport

* Introduction

Provides some basic randomness tools.

* Features

Numbers, characters

- ~random-whole~
- ~random-range~
- ~random-digit~
- ~random-alpha~

Array index or subscripts

- ~random-array-index~
- ~random-array-subscripts~

Random elements

- ~random-nth~
- ~random-char~
- ~random-svref~
- ~random-elt~
- ~random-aref~

Samplef generic-function

- ~samplef~

Bias maker (use with ~samplef~)

- ~make-bias~

Shuffles

- ~nshuffle~
- ~shuffle~

See the TODO document for future ideas and features that might appear
here.

* Purpose

This is here shared with the idea that some might find it useful for
personal experiments and toys--that's all I'm using it for. It might
also be cautionarily if not pedagogically useful. All that said, it
should not be expected to have any desireable characteristics or be
useful in any way.

Non-personal use (for example, commercial) is forbidden.

Non-casual personal use is strongly discouraged.

Really, the main purpose here is simply a self-demonstration of module
making that I can reuse for making more complex projects.

* Instructions

To use:

1. Clone repository
   - *nix, GitHub :: =git clone https://github.com/wobh/org.wobh.common-lisp.tools.chance.git ${XDG_DATA_HOME}/common-lisp/source/org.wobh.common-lisp.tools.chance=
2. in REPL ~(require "asdf")~ (as needed)
3. ~(asdf:load-system :org.wobh.common-lisp.tools.chance)~

The test package is simply Lisp assertions and loads with the rest of
the system. If the system loads without errors all the tests passed.

The package defines a nickname of ~chance~ for convenience.

* COMMENT org settings
#+options: ':nil *:t -:t ::t <:t H:6 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
