#+title: Chance TODO
#+date: <2023-03-04 Sat>
#+author: William Clifford
#+email: will@wobh.org

* DOING Implement PCG Random Number Generation?

This seems like it might be fun, and as a generator would have a lot
of useful properties we wouldn't necessarily get from an
implementation's ~make-random-state~:

- https://github.com/imneme/pcg-c-basic

Not sure if we can make it a ~*random-state*~ compatible thing without
some heavy lifting, but maybe!

- https://www.pcg-random.org/

Update: This is happening.

* [0/3] misc clean up and reorganize

- [ ] rename ~make-bias~
  - ~make-biased-sampler~ ?
  - ~make-biased-sequence-sampler~ ?
- [ ] reorganize "samplers" functions
  - include ~make-bias~ (under new name) in the sequence-samplers
- [ ] setup ~random-index~
  - ~random-sequence-index~
  - ~random-position~ <- this would agree with the sequence function

* TODO setup resevoir sampling

This will allow implementation of samplers for:

- lists (traversing them only once)
  - alists
  - plists
  - trees
- hash-tables

This might provide some insight into a better way to write (maybe even
just naming things) in the biased-sampler functions.

** References
- https://en.wikipedia.org/wiki/Reservoir_sampling
- https://lisptips.com/post/43404489000/the-tree-walkers-of-cl
  - use the tree-equal technique to walk the tree to be sampledx

* TODO add tests for shuffling, sampling, using biases
* TODO generate non-repeating sequences

Based on:

- http://preshing.com/20121224/how-to-generate-a-sequence-of-unique-random-integers/

Possibly could be integrated with PCG.

I attempted this in a small way here:

https://exercism.io/my/solutions/7943ffe042e24686b09740553141c8a4?iteration_idx=3

but I'm sure there are bugs.

* TODO improve test reporting
* TODO setup asdf test op

https://common-lisp.net/project/asdf/asdf/Predefined-operations-of-ASDF.html#test_002dop

* TODO Toys

I don't know if this should be included here or belongs in a separate
system but, it would be fun to have things like:

- dice
- cards
- various fortune-telling systems
  - tarot
  - i-ching
  - magic 8-ball

* TODO Fakery

There's a number of libraries out there that generate fake info in
various formats and that seems like a fun thing to build. It would
resonate with another interest of mine: grammars!
